apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-{{.Values.rhacm.config.version}}
  installPlanApproval: Automatic
  name: advanced-cluster-management